version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: task_manager_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: taskmanager
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
